---
title: "Early Results"
author: "Evan Goodgee"
date: "2025-10-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Loading libraries
library(readr)
library(dplyr)
library(readxl)
library(ggplot2)
library(gtsummary)
```

```{r}
# Importing college scorecard data
SC2014 = read_csv("Data/College_Scorecard_Raw_Data_05192025/MERGED2017_18_PP.csv")

SC = SC2014 %>% 
  select(UNITID,
         INSTNM,
         ICLEVEL,
         AVGFACSAL,
         PFTFAC)

MJRdata = read_csv("Data/College_Scorecard_Raw_Data_05192025/FieldOfStudyData1819_1920_PP.csv")

# Creating dummy variables for public/private
MJRdata$Public = ifelse(MJRdata$CONTROL == "Public", 1, 0)
MJRdata$Private = ifelse(MJRdata$CONTROL == "Private, nonprofit", 1, 0)

# Removing strings and making income columns numeric
MJRdata$EARN_MDN_1YR[MJRdata$EARN_MDN_1YR == "PS"] = NA
MJRdata$EARN_MDN_4YR[MJRdata$EARN_MDN_4YR == "PS"] = NA
MJRdata$EARN_MDN_1YR = as.numeric(MJRdata$EARN_MDN_1YR)
MJRdata$EARN_MDN_4YR = as.numeric(MJRdata$EARN_MDN_4YR)

MJR = MJRdata %>% 
  filter(CREDLEV == 3) %>% 
  filter(CONTROL %in% (c("Public", "Private, nonprofit"))) %>%
  select(UNITID,
        Public,
        Private,
        CIPCODE, 
        CIPDESC, 
        CREDLEV,
        EARN_MDN_1YR,
        EARN_MDN_4YR
  )



# Importing IPEDS data
IPEDS = read_excel("Data/IPEDS_2018-19/ADM2018.xlsx")
IPEDS = IPEDS %>% select(UNITID,
                         AdmissionPct,
                         ACTCM75,
                         )

# Importing IPEDS Carnegie Classification data
Class = read_excel("Data/IPEDS_2018-19/HD2018.xlsx")
Classification = Class %>% select(UNITID, CCBASIC, CARNEGIE)
```

```{r}
# Merging Datasets
Merged = merge(IPEDS, SC, by = "UNITID")
MoreMerged = merge(Merged, Classification)

# Selecting required variables and filtering out non-four-year and non-standard institutions
EducationData = merge(MoreMerged, MJR, by  = "UNITID") %>% 
  select(UNITID, INSTNM, ICLEVEL, CCBASIC, everything())  %>% 
  filter(ICLEVEL == 1) %>% 
  filter(CCBASIC %in% c(15,16,17,18,19,20,21,22))
```


```{r}
# Creating dummy variables for Carnegie Classification

# Research University - Very High Research Activity
EducationData$RUVH = ifelse(EducationData$CCBASIC == 15, 1, 0)

# Research University - High Research Activity
EducationData$RUH = ifelse(EducationData$CCBASIC == 16, 1, 0)

# Research University 
EducationData$RU = ifelse(EducationData$CCBASIC == 17, 1, 0)

# Large Master's Programs
EducationData$LMP = ifelse(EducationData$CCBASIC == 18, 1, 0)

# Medium Master's Programs
EducationData$MMP = ifelse(EducationData$CCBASIC == 19, 1, 0)

# Small Master's Programs
EducationData$SMP = ifelse(EducationData$CCBASIC == 20, 1, 0)

# Baccalaureate College - Arts and Sciences (Liberal Arts)
EducationData$BCAS = ifelse(EducationData$CCBASIC == 21, 1, 0)

# Baccalaureate College - Diverse Fields
EducationData$BCG = ifelse(EducationData$CCBASIC == 22, 1, 0)

#
EducationData$CCGroup = ifelse(EducationData$CCBASIC %in% c(15,16,17), "Doctoral",
                               ifelse(EducationData$CCBASIC %in% c(18,19,20), "Master's",
                                      "Baccelaureate"))
  


# Reconfiguring CCBASIC to create visualizations
EducationData$CCBASIC[EducationData$CCBASIC == 15] = "RUVH"
EducationData$CCBASIC[EducationData$CCBASIC == 16] = "RUH"
EducationData$CCBASIC[EducationData$CCBASIC == 17] = "RU"
EducationData$CCBASIC[EducationData$CCBASIC == 18] = "LMP"
EducationData$CCBASIC[EducationData$CCBASIC == 19] = "MMP"
EducationData$CCBASIC[EducationData$CCBASIC == 20] = "SMP"
EducationData$CCBASIC[EducationData$CCBASIC == 21] = "BCAS"
EducationData$CCBASIC[EducationData$CCBASIC == 22] = "BCG"
```

```{r}
# Creating a data set with just Mathematics Majors to isolate earnings differences
math = EducationData %>% filter(CIPCODE == 2701)

# Creating a data set with just Biology Majors to isolate earnings differences
bio = EducationData %>% filter(CIPCODE == 2601)
```


```{r}
# Linear Regression Model
options(scipen = 999)
lm4Year = lm(log(EARN_MDN_4YR) ~ RUVH + RUH + RU + LMP + MMP + SMP + BCG + AdmissionPct + ACTCM75 + AVGFACSAL, data = math)
rsq = summary(lm4Year)$r.squared
adj_rsq = summary(lm4Year)$adj.r.squared

summary(lm4Year)
tbl = tbl_regression(lm4Year) %>%
  modify_footnote(
    update = everything() ~paste0("R-squared = ", round(rsq, 3),
                                  ", Adj. R-squared = ", round(adj_rsq, 3))
  )

tbl %>% as_gt() %>% gt::gtsave("regression_table.html")
tbl
browseURL("regression_table.html")
```



```{r}
# Testing Validity of Assumptions for Multiple Linear Regression
# Normality of residuals
res = resid(lm4Year)
qqnorm(res)

# Multicolinearity
regVar = math %>% select(EARN_MDN_4YR,RUVH, RUH, RU, LMP, MMP, SMP, BCG, BCAS,  AdmissionPct, ACTCM75, AVGFACSAL)
cor(regVar, use = "pairwise.complete.obs")

# Homoscedasticity
plot(fitted(lm4Year), res)

write_csv(EducationData, file = "MergedEducationData.csv")
majorNumbers = EducationData %>% count(CIPDESC)
```
