title: "Early Results Institutional Comp"

author: "Evan Goodgee"

date: "2025-10-29"

output: html_document

------------------------------------------------------------------------

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Loading libraries

library(readr)

library(dplyr)

library(readxl)

library(ggplot2)

library(gtsummary)
```

```{r}
# Importing college scorecard data

SC2014 <- read_csv("Data/College_Scorecard_Raw_Data_05192025/MERGED2014_15_PP.csv")

SC = SC2014 %>% select(UNITID, INSTNM, ICLEVEL, COSTT4_A, AVGFACSAL, PFTFAC, C150_4, RET_FT4, PRGMOFR, CIPCODE1, MD_EARN_WNE_P6, MD_EARN_WNE_P8, MD_EARN_WNE_P10)

# Importing IPEDS data

IPEDS = read_excel("Data/IPEDS_2014-15_Final/ADM2014.xlsx")

# Importing IPEDS Carnegie Classification data

Car = read_excel("Data/IPEDS_2014-15_Final/HD2014.xlsx")

Classification = Car %>% select(UNITID, CCBASIC)
```

```{r}
# Merging Datasets

Merged = merge(IPEDS, SC, by = "UNITID")

# Converting and renaming income variables

Merged$Income10 = as.double(Merged$MD_EARN_WNE_P10)

Merged$Income8 = as.double(Merged$MD_EARN_WNE_P8)

Merged$Income6 = as.double(Merged$MD_EARN_WNE_P6)

# Selecting required variables and filtering out non-four-year and non-standard institutions

EducationData = merge(Merged, Classification, by  = "UNITID") %>% select(UNITID, INSTNM, ICLEVEL, CCBASIC, everything(), -SecondaryTranscript, -SecondaryGPA, -TestScores, -CIPCODE1, -PRGMOFR, -MD_EARN_WNE_P6, -MD_EARN_WNE_P8, -MD_EARN_WNE_P10)  %>% filter(ICLEVEL == 1) %>% filter(CCBASIC %in% c(15,16,17,18,19,20,21,22))

View(EducationData)
```

```{r}
# Creating dummy variables for Carnegie Classification

# Research University - Very High Research Activity

EducationData$RUVH = ifelse(EducationData$CCBASIC == 15, 1, 0)

# Research University - High Research Activity

EducationData$RUH = ifelse(EducationData$CCBASIC == 16, 1, 0)

# Research University 

EducationData$RU = ifelse(EducationData$CCBASIC == 17, 1, 0)

# Large Master's Programs

EducationData$LMP = ifelse(EducationData$CCBASIC == 18, 1, 0)

# Medium Master's Programs

EducationData$MMP = ifelse(EducationData$CCBASIC == 19, 1, 0)

# Small Master's Programs

EducationData$SMP = ifelse(EducationData$CCBASIC == 20, 1, 0)

# Baccalaureate College - Arts and Sciences (Liberal Arts)

EducationData$BCAS = ifelse(EducationData$CCBASIC == 21, 1, 0)

# Baccalaureate College - Diverse Fields

EducationData$BCG = ifelse(EducationData$CCBASIC == 22, 1, 0)

#

EducationData$CCGroup = ifelse(EducationData$CCBASIC %in% c(15,16,17), "Doctoral",

                               ifelse(EducationData$CCBASIC %in% c(18,19,20), "Master's", "Baccelaurate"))

# Reconfiguring CCBASIC to create visualizations
EducationData$CCBASIC[EducationData$CCBASIC == 15] = "RUVH"
EducationData$CCBASIC[EducationData$CCBASIC == 16] = "RUH"
EducationData$CCBASIC[EducationData$CCBASIC == 17] = "RU"
EducationData$CCBASIC[EducationData$CCBASIC == 18] = "LMP"
EducationData$CCBASIC[EducationData$CCBASIC == 19] = "MMP"
EducationData$CCBASIC[EducationData$CCBASIC == 20] = "SMP"
EducationData$CCBASIC[EducationData$CCBASIC == 21] = "BCAS"
EducationData$CCBASIC[EducationData$CCBASIC == 22] = "BCG"
```

```{r}
# Linear Regression Model

lm10Year = lm(log(Income10) ~ RUVH + RUH + RU + LMP + MMP + SMP + BCG + AdmissionPct + ACTCM75 + log(AVGFACSAL), data = EducationData)

rsq = summary(lm10Year)$r.squared
adj_rsq = summary(lm10Year)$adj.r.squared
tbl = tbl_regression(lm10Year) %>%
  modify_footnote(
    update = everything() ~paste0("R-squared = ", round(rsq, 3),
                                  ", Adj. R-squared = ", round(adj_rsq, 3))
  )

tbl %>% as_gt() %>% gt::gtsave("regression_table.html")
tbl
browseURL("regression_table.html")
summary(lm10Year)

```

# Testing validity of linear regression assumptions

```{r}
# Normality of residuals
res = resid(lm10Year)
qqnorm(res)

# Multicolinearity
regVar = EducationData %>% select(Income10,RUVH, RUH, RU, LMP, MMP, SMP, BCG, BCAS,  AdmissionPct, ACTScore75, log(AVGFACSAL))
cor(regVar, use = "pairwise.complete.obs")

# Homoscedasticity
plot(fitted(lm10Year), res)
```

```{r}
hist(EducationData$PFTFAC)

ggplot(data = EducationData, aes(x = CCBASIC, y = Income10)) +
  geom_boxplot() +
  facet_wrap(~CCGroup, scales = "free_x", strip.position = "bottom") +
  ggtitle("Average Median 10 Year Income by Carnegie Classification") +
  xlab("Carnegie Classification") +
  ylab("Average Median 10 Year Income") +
  theme_classic() + 
  theme(legend.position = "none")
```

## Creating Visuals for First Draft

```{r}
EducationData1 = read_csv("Data/MergedEducationData.csv")
Salary = EducationData %>% select(Income10, UNITID)
EducationData2 = merge(EducationData1, Salary)
EducationData2$PELL_RT = as.numeric(EducationData2$PELL_RT)

lm10Year = lm(log(Income10) ~ RUVH + RUH + RU + LMP + MMP + SMP + BCG + Public + AdmissionPct + GradRate + PELL_RT + ACTCM75 + log(AVGFACSAL), data = EducationData2)

summary(lm10Year)

# Summary Table of model

rsq = summary(lm10Year)$r.squared
adj_rsq = summary(lm10Year)$adj.r.squared
tbl = tbl_regression(lm10Year, intercept = TRUE) %>%
  modify_footnote(
    update = everything() ~paste0("R-squared = ", round(rsq, 3),
                                  ", Adj. R-squared = ", round(adj_rsq, 3))
  )

tbl %>% as_gt() %>% gt::gtsave("regression_table.html")
tbl
browseURL("regression_table.html")
summary(lm10Year)

# Boxplot of earnings
ggplot(data = EducationData2, aes(x = CCBASIC, y = Income10)) +
  geom_boxplot() +
  facet_wrap(~CCGroup, scales = "free_x", strip.position = "bottom") +
  ggtitle("Median 10 Year Income by Carnegie Classification") +
  ylab("Median Earnings 10 Years After Graduation (USD)") +
  xlab("") +
  theme_classic() + 
  theme(legend.position = "none", text = element_text(family = "Times New Roman"))

# Normality of Residuals
res = resid(lm10Year)
qqnorm(res) + 
  qqline(res)

# Multicolinearity
vif(lm10Year)

# Homoscedasticity
plot(fitted(lm10Year), res)
```

## Calculating impact on dependent variable through exponentiation of betas

```{r}
exp(0.0584017)
exp(0.0825882)
exp(0.0702864)
exp(0.0653868)
exp(0.0644686)
exp(0.0525850)
exp(0.0501843)
exp(-0.0812914)
exp(-0.0447051)
exp(0.1030632)
exp(0.3481858)
exp(0.0080790)
exp(0.3279907)
```
