---
title: "Early Results"
author: "Evan Goodgee"
date: "2025-10-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Loading libraries
library(readr)
library(dplyr)
library(readxl)
library(ggplot2)
library(gtsummary)
```

```{r}
# Importing college scorecard data
SC2014 <- read_csv("Data/College_Scorecard_Raw_Data_05192025/MERGED2014_15_PP.csv")

SC = SC2014 %>% select(UNITID, INSTNM, ICLEVEL, COSTT4_A, AVGFACSAL, PFTFAC, C150_4, RET_FT4, PRGMOFR, CIPCODE1, MD_EARN_WNE_P6, MD_EARN_WNE_P8, MD_EARN_WNE_P10)

# Importing IPEDS data
IPEDS = read_excel("Data/IPEDS_2014-15_Final/ADM2014.xlsx")

# Importing IPEDS Carnegie Classification data
Car = read_excel("Data/IPEDS_2014-15_Final/HD2014.xlsx")
Classification = Car %>% select(UNITID, CCBASIC)

```

```{r}
# Merging Datasets
Merged = merge(IPEDS, SC, by = "UNITID")

# Converting and renaming income variables
Merged$Income10 = as.double(Merged$MD_EARN_WNE_P10)
Merged$Income8 = as.double(Merged$MD_EARN_WNE_P8)
Merged$Income6 = as.double(Merged$MD_EARN_WNE_P6)

# Selecting required variables and filtering out non-four-year and non-standard institutions
EducationData = merge(Merged, Classification, by  = "UNITID") %>% select(UNITID, INSTNM, ICLEVEL, CCBASIC, everything(), -SecondaryTranscript, -SecondaryGPA, -TestScores, -CIPCODE1, -PRGMOFR, -MD_EARN_WNE_P6, -MD_EARN_WNE_P8, -MD_EARN_WNE_P10)  %>% filter(ICLEVEL == 1) %>% filter(CCBASIC %in% c(15,16,17,18,19,20,21,22))



```


```{r}
# Creating dummy variables for Carnegie Classification

# Research University - Very High Research Activity
EducationData$RUVH = ifelse(EducationData$CCBASIC == 15, 1, 0)

# Research University - High Research Activity
EducationData$RUH = ifelse(EducationData$CCBASIC == 16, 1, 0)

# Research University 
EducationData$RU = ifelse(EducationData$CCBASIC == 17, 1, 0)

# Large Master's Programs
EducationData$LMP = ifelse(EducationData$CCBASIC == 18, 1, 0)

# Medium Master's Programs
EducationData$MMP = ifelse(EducationData$CCBASIC == 19, 1, 0)

# Small Master's Programs
EducationData$SMP = ifelse(EducationData$CCBASIC == 20, 1, 0)

# Baccalaureate College - Arts and Sciences (Liberal Arts)
EducationData$BCAS = ifelse(EducationData$CCBASIC == 21, 1, 0)

# Baccalaureate College - Diverse Fields
EducationData$BCG = ifelse(EducationData$CCBASIC == 22, 1, 0)

#
EducationData$CCGroup = ifelse(EducationData$CCBASIC %in% c(15,16,17), "Doctoral",
                               ifelse(EducationData$CCBASIC %in% c(18,19,20), "Master's",
                                      "Baccelaurate"))
  


# Reconfiguring CCBASIC to create visualizations
EducationData$CCBASIC[EducationData$CCBASIC == 15] = "RUVH"
EducationData$CCBASIC[EducationData$CCBASIC == 16] = "RUH"
EducationData$CCBASIC[EducationData$CCBASIC == 17] = "RU"
EducationData$CCBASIC[EducationData$CCBASIC == 18] = "LMP"
EducationData$CCBASIC[EducationData$CCBASIC == 19] = "MMP"
EducationData$CCBASIC[EducationData$CCBASIC == 20] = "SMP"
EducationData$CCBASIC[EducationData$CCBASIC == 21] = "BCAS"
EducationData$CCBASIC[EducationData$CCBASIC == 22] = "BCG"
```

```{r}
# Linear Regression Model
lm10Year = lm(log(Income10) ~ RUVH + RUH + RU + LMP + MMP + SMP + BCG + AdmissionPct + ACTScore75 + PFTFAC, data = EducationData)
rsq = summary(lm10Year)$r.squared
adj_rsq = summary(lm10Year)$adj.r.squared

tbl = tbl_regression(lm10Year) %>%
  modify_footnote(
    update = everything() ~paste0("R-squared = ", round(rsq, 3),
                                  ", Adj. R-squared = ", round(adj_rsq, 3))
  )

tbl %>% as_gt() %>% gt::gtsave("regression_table.html")
tbl
browseURL("regression_table.html")
```



```{r}
hist(EducationData$PFTFAC)
ggplot(data = EducationData, aes(x = CCBASIC, y = Income10, color = CCGroup, )) +
  geom_boxplot() +
  facet_wrap(~CCGroup, scales = "free_x", strip.position = "bottom") +
  ggtitle("Average Median 10 Year Income by Carnegie Classification") +
  xlab("Carnegie Classification") +
  ylab("Average Median 10 Year Income") +
  theme_classic() + 
  theme(legend.position = "none")
```


