---
title: "First Draft"
format: html
editor: visual
---

## Downloading Libraries and Data

```{r}
library(readr)
library(dplyr)
library(ggplot2)
library(gtsummary)
library(car)

EducationData = read_csv("Data/MergedEducationData.csv")
EducationData$PELL_RT = as.numeric(EducationData$PELL_RT)

majorNumbers = EducationData %>% count(CIPDESC)

# Creating new dummy variables for regression
EducationData$Doctoral = ifelse(EducationData$CCGroup == "Doctoral", 1, 0)
EducationData$Masters = ifelse(EducationData$CCGroup == "Master's", 1, 0)
EducationData$Baccelaureate = ifelse(EducationData$CCGroup == "Baccelaureate", 1, 0)

# Creating subsets of data for specific degree types
math = EducationData %>% filter(CIPCODE %in% c(2701, 2703, 2706, 2799))
bio = EducationData %>% filter(CIPCODE == 2601)
humanities = EducationData %>% filter(CIPCODE %in% c(2301, 2401, 2313, 0901, 1609, 3801, 3802, 5401)) 
```

## Creating regression models

```{r}
# Regression for math majors
lm4YearMath = lm(log(EARN_MDN_4YR) ~ RUVH + RUH + RU + LMP + MMP + SMP + BCG + AdmissionPct + ACTCM75 + log(AVGFACSAL), data = math)

# Regression for biology majors
lm4YearBio = lm(log(EARN_MDN_4YR) ~ RUVH + RUH + RU + LMP + MMP + SMP + BCG + AdmissionPct + ACTCM75 + log(AVGFACSAL), data = bio)

# Regression for english majors
lm4YearHumanities = lm(log(EARN_MDN_4YR) ~ RUVH + RUH + RU + LMP + MMP + SMP + BCG + Public + AdmissionPct + GradRate + PELL_RT + ACTCM75 + log(AVGFACSAL), data = humanities)

summary(lm4YearBio)
summary(lm4YearMath)
summary(lm4YearHumanities)

namath = na.omit(math)
namath %>% count(CCBASIC)

biomath = na.omit(bio)
biomath %>% count(CCBASIC)

naHumanities = na.omit(humanities)
naHumanities %>% count(CCBASIC)
```

## Testing Model Validity

```{r}
# Normality of residuals
res = resid(lm4YearHumanities)
qqnorm(res)

hist(res)

# Multicolinearity
regVar = humanities %>% select(EARN_MDN_4YR,RUVH, RUH, RU, LMP, MMP, SMP, BCG, BCAS,  AdmissionPct, ACTCM75, AVGFACSAL)
cor(regVar, use = "pairwise.complete.obs")

vif(lm4YearHumanities)

# Homoscedasticity
plot(fitted(lm4YearHumanities), res)
```

## Creating a new regression with institution types grouped

```{r}
lm4YearHumanitiesGrouped = lm(log(EARN_MDN_4YR) ~ Doctoral + Masters + Public + AdmissionPct + GradRate + PELL_RT + log(AVGFACSAL), data = humanities)
summary(lm4YearHumanitiesGrouped)
```

## Testing Model Validity

```{r}
# Normality of residuals
res = resid(lm4YearHumanitiesGrouped)
qqnorm(res)

# Multicolinearity
regVar = humanities %>% select(EARN_MDN_4YR, Masters, Doctoral, Baccelaureate, AdmissionPct, ACTCM75, AVGFACSAL)
cor(regVar, use = "pairwise.complete.obs")

vif(lm4YearHumanitiesGrouped)

# Homoscedasticity
plot(fitted(lm4YearHumanitiesGrouped), res)
```

## Creating Paper Ready Visuals

```{r}
# Model summary table
rsq = summary(lm4YearHumanities)$r.squared
adj_rsq = summary(lm4YearHumanities)$adj.r.squared
tbl = tbl_regression(lm4YearHumanities, intercept = TRUE) %>%
  modify_footnote(
    update = everything() ~paste0("R-squared = ", round(rsq, 3),
                                  ", Adj. R-squared = ", round(adj_rsq, 3))
  )

tbl %>% as_gt() %>% gt::gtsave("regression_table.html")
tbl
browseURL("regression_table.html")
summary(lm4YearHumanities)

# Normality of Residuals
res = resid(lm4YearHumanities)
qplot(sample = res) +
  stat_qq() +
  stat_qq_line() + 
  theme_classic() +
  labs(x = "Theoretical Quantiles", y ="Sample Quantiles", title = "Normal Q-Q Plot")
  
# Multicolinearity
vif(lm4YearHumanities)

# Homoscedasticity
ggplot(data.frame(res = res), aes(x = fitted(lm4YearHumanities), y = res)) +
  geom_point() +
  geom_smooth() +
  labs(x = "Fitted Values", y = "Residuals", title = "Residual Plot") +
  theme_classic() + 
  coord_cartesian(ylim = c(-0.75, 0.75))
```

## Exponentiating the coefficients to put in percentage terms

```{r}
exp(0.022173)
exp(0.038081)
exp(0.045948)
exp(0.041916)
exp(0.009524)
exp(0.030669)
exp(0.020893)
exp(-0.064066)
exp(-0.063737)
exp(0.051402)
exp(0.217936)
exp(0.002444)
exp(0.215921)
```
